### ISSUE TITLE
hide/show cursor

### ISSUE THREAD

**Issue by ricardogj08** [osch/lua-nocurses#1]
Considerate add hide and show cursor? regards!!

**Comment by osch** [comment]
yes, this would be an improvement

**Comment by osch** [comment]
Hide and show cursor in now implemented in 95606c5 and published in release [v0.0.2](https://github.com/osch/lua-nocurses/releases/tag/v0.0.2)

**Comment by ricardogj08** [comment]
awesome! thanks 🎉
